### Bibliotecas

In [7]:
# Instalação manual de bibliotecas
!pip install numpy matplotlib pandas seaborn
# Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb


# WARNING: N entendi o que baixar na 3C TODO ver isso depois
# CUDA. Lindo. Isso vai ser divertido: https://github.com/CannyLab/tsne-cuda

# 1) Dada a base de dados Haberman's Survival (disponibilizada em http://archive.ics.uci.edu/dataset/43/haberman+s+survival), obtenha:


## d) O histograma com 8 bins de cada um dos atributos para cada uma das classes (gere gráficos dos histogramas com cores diferentes para cada classe);
## e) Gere um gráfico 3D das amostras, identificando cada classe. Analise o gráfico e informe se a tarefa de classificação é fácil ou difícil e justifique a sua resposta.

Leitura dos dados

In [32]:

#Faz a leitura do arquivo com os dados
#header = None --> o arquivo não tem cabeçalho
#names --> coloca nomes para cada coluna
data = pd.read_csv('data/haberman.data', header = None, names = ['age', 'op_year', 'pos_nodes', 'survived'])
data.head()
# data.describe()

age  op_year  pos_nodes  survived
0   30       64          1         1
1   30       62          3         1
2   30       65          0         1
3   31       59          2         1
4   31       65          4         1

## a) A média e variância de cada um dos atributos;

In [18]:
# seleciona apenas atributos de entrada
faixa = np.arange(0,3)
print(faixa)

[0 1 2]


In [14]:
# Imprime média e variância de cada atributo
print('Média')
print(data.iloc[:,faixa].mean())

print('\r\nVariância')
print(data.iloc[:,faixa].var())

Média
age        52.457516
op_year    62.852941
dtype: float64

Variância
age        116.714583
op_year     10.558631
dtype: float64


## b) A média e variância de cada um dos atributos para cada uma das classes;

In [37]:
# Como pegar atributos filtrados por classe
# Extrai todos os valores únicos e os coloca num vetor
classes = data['survived'].unique()
# print(classes)

for i in range(0,classes.size):
    data_select = data[data['survived'] == classes[i]]
    print(f"Média 'survived' == {classes[i]}\n")
    print(data_select.iloc[:,faixa].mean())
    print("\n")
    print(f"Variância 'survived' == {classes[i]}\n")
    print(data_select.iloc[:,faixa].var())
    print("\n\n")


Média 'survived' == 1

age          52.017778
op_year      62.862222
pos_nodes     2.791111
dtype: float64


Variância 'survived' == 1

age          121.267540
op_year       10.387183
pos_nodes     34.460635
dtype: float64



Média 'survived' == 2

age          53.679012
op_year      62.827160
pos_nodes     7.456790
dtype: float64


Variância 'survived' == 2

age          103.370679
op_year       11.169753
pos_nodes     84.376235
dtype: float64





## c) A matriz de coeficientes de correlação;

In [42]:
#Usamos numpy para realizar os cálculos
eigValues, eigVectors = np.linalg.eig(data.iloc[:,faixa].corr())
print(f" {eigValues}")
print()
print(eigVectors)


 [1.11137003 0.89217623 0.99645374]

[[ 0.70131829  0.71275488  0.01153822]
 [ 0.57789155 -0.57794675  0.57621082]
 [-0.41736555  0.39743934  0.81721965]]
